/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wenba_com_androidtest_jni_JniTest */

#ifndef _Included_wenba_com_androidtest_jni_JniTest
#define _Included_wenba_com_androidtest_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wenba_com_androidtest_jni_JniTest
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_wenba_com_androidtest_jni_JniTest_set
  (JNIEnv *, jobject, jstring);

/*
 * Class:     wenba_com_androidtest_jni_JniTest
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_wenba_com_androidtest_jni_JniTest_get
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
